name: lint-and-test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "**"  # Skip re-linting when tags are added

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools importlib-metadata
        pip install poetry
        poetry install

    - name: Run flake8
      run: poetry run flake8 .

    - name: Run mypy
      run: poetry run mypy .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools importlib-metadata
        pip install tox-gh-actions

    - name: Run tests w/tox
      run: tox

    - name: Cache coverage for ${{ matrix.python-version }}
      uses: actions/upload-artifact@v2
      with:
        name: cov_py${{ matrix.python-version }}
        path: .coverage

  combine-cov:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Pull coverage workflow artifacts
      uses: actions/download-artifact@v2
      with:
        path: cov_cache/

    - name: Install cov & combine
      run: |
        pip install coverage
        coverage combine ./cov_cache/**/.coverage

    - name: Report coverage
      run: |
        coverage report -m --skip-covered
        coverage html

    - name: Publish cov HTML
      uses: actions/upload-artifact@v2
      with:
        path: htmlcov/
        name: cov_report_html
